export const ADMIN_ROUTE = 'admin'
export const LOGIN_ROUTE = 'signin'
export const REGISTRATION_ROUTE = 'signup'
export const SHOP_ROUTE = 'shop'
export const CART_ROUTE = 'cart'
export const PRODUCT_ROUTE = 'product/:id'